export type InputsValue = {

    property_type_id: string,
    sub_type_id: string,
    tenancy_id: string,
    property_name: String,
    address: string,
    city: string,
    state_id: string,
    country:string
    tenant_brand_id: string[],
    region_id: string[],
    zipcode: string,
    cap: number,
    closed_cap: number,
    price: number,
    sold_price: number,
    lease_type_id:string,
    credit_id:string[],
    corp_franchisee_unit_count:string,
    noi: number,
    closing_noi: number,
    rent_bump:string,
    rent_bump_text:string,
    lease_start:string,
    lease_end:string,
    list_date:string,
    list_closing_date:string,
    tenant_unit:string,
    vacancy_perc:number,
    traffic:null,
    pop_1_mile:number,
    pop_3_mile:number,
    pop_5_mile:number,
    hh_1_mile:number,
    hh_3_mile:number,
    hh_5_mile:number,
    size_sqft:number,
    per_sqft_price:number,
    per_sqft_rent_price:number,
    lot_ac:number,
    year_built:string,
    unit_price:number,
    assumptions:any[],
    reported_sales:number,
    lat:number,
    long:number

}